### ISSUE TITLE
PowerShell (Full) crashes on fully patched Windows 10 1703

### ISSUE THREAD

**Issue by knoxyca** [Jaykul/Jupyter-PowerShell#8]
Have tried on two systems running Windows 10 1703, and PowerShell (Full) crashes immediately upon opening the notebook. Issue does not occur on Windows 10 Insider build system.

```
[I 21:07:07.375 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 21:07:18.486 NotebookApp] Creating new notebook in
[I 21:07:20.970 NotebookApp] Kernel started: 00d310c9-98c4-4194-9746-de1826ea36d2

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor(Func`3 filter, Boolean includeScopes)
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggerFactory factory, Boolean includeScopes)
   at Jupyter.PowerShell.Kernel.Main(String[] args)
[I 21:07:26.927 NotebookApp] KernelRestarter: restarting kernel (1/5)

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor(Func`3 filter, Boolean includeScopes)
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggerFactory factory, Boolean includeScopes)
   at Jupyter.PowerShell.Kernel.Main(String[] args)
[I 21:07:29.947 NotebookApp] Interrupted...
[I 21:07:29.950 NotebookApp] Shutting down kernels
[I 21:07:29.953 NotebookApp] Kernel shutdown: 00d310c9-98c4-4194-9746-de1826ea36d2
```

**Comment by Jaykul** [comment]
I'm going to add a -d for debug and -c for console switch to the kernel for now, and not log to either by default -- that should sort this.
